const products = [
  {
    _id: 1,
    name: "Saparale",
    region: "Sartène",
    description: "tagada tsoin tsoin",
    price: 36,
    type: "vins",
    category: "rouges",
    subCategory: "corses",
    choice: true,
    visible: true,
  },
  {
    _id: 6,
    name: "Casteddu",
    region: "Sartène",
    description: "tagada tsoin tsoin",
    price: 36,
    type: "vins",
    category: "rouges",
    subCategory: "millesimes",
    choice: false,
    visible: true,
  },
  {
    _id: 2,
    name: "Venturi",
    region: "Sartène",
    description: "tagada tsoin tsoin",
    price: 45,
    type: "vins",
    category: "blancs",
    choice: false,
    visible: true,
  },
  {
    _id: 4,
    name: "Saparale",
    region: "Sartène",
    description: "tagada tsoin tsoin",
    price: 36,
    type: "vins",
    category: "blancs",
    choice: false,
    visible: true,
  },
  {
    _id: 3,
    name: "Heineken",
    region: "",
    description: "25cl",
    price: 3.5,
    type: "bieres",
    category: "",
    choice: false,
    visible: true,
  },
];

export default products;
